### ISSUE TITLE
multipart/signed not implemented: Attached "signature.asc" messages not verified

### ISSUE THREAD

**Issue by maxxer** [Zimbra-Community/pgp-zimlet#136]
I got a signed email, but the signature was in a separate attachment named *signature.asc*. The zimlet isn't currently verifying this kind of mails.

The mail I got was generated by *Apple Mail*. Relevant headers:

```
x-pgp-agent: GPGMail 2.5.2
x-mailer: Apple Mail (2.1878.6)
Content-Type: multipart/signed;
	boundary="Apple-Mail=_4C1068A3-6CA1-4F8D-9F53-805D586D67FC";
	protocol="application/pgp-signature"; micalg=pgp-sha1
MIME-Version: 1.0
```

I mailed you a test case.

**Comment by barrydegraaff** [comment]
From: info@barrydegraaff.tk
To: list@openpgpjs.org
Subject: How-to verify multipart/signed?
Date: Thu, 3 Dec 2015 09:38:16 +0000

Hi Folks,

Is it possible to verify multipart/signed pgp/mime messages with OpenPGP.js?

https://tools.ietf.org/html/rfc1847#page-3
See attached example from enigmail.

Thanks Barry

**Comment by barrydegraaff** [comment]
I don't know how to implement this yet, so if someone is reading this and can help, please let me know.

**Comment by barrydegraaff** [comment]
I will not further pursue pgp/mime and this feature in particular, as it would take quite some effort to add and the benefits are minimal.

**Comment by barrydegraaff** [comment]
see: https://github.com/Zimbra-Community/pgp-zimlet/issues/173
