### ISSUE TITLE
Email not decrypted when read panel is desactivated

### ISSUE THREAD

**Issue by manens** [Zimbra-Community/pgp-zimlet#137]
To reproduce: 
1) Desactivate Reading Pane
2) Open email

The email stay encrypted

**Comment by barrydegraaff** [comment]
duplicate from https://github.com/Zimbra-Community/pgp-zimlet/issues/110

Right now pgp-zimlet only is implemented in the reading pane. Its not a bug per-se, it is just a limitation of the current implementation. If someone can code it, or donate some time or money, this feature may be build in the future.
