### ISSUE TITLE
clarify

### ISSUE THREAD

**Issue by ba1020** [Zimbra-Community/pgp-zimlet#138]
so your zimlet is now deployed in

/opt/zimbra/zimlets-deployed/_dev

makes it a lot clearer

**Comment by barrydegraaff** [comment]
/opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_zimbra_openpgp
To be exact. 

zmzimletctl often results in cache problems, that people don't understand, and result in weird half-installed updates. That then end up as emails asking people for support.

Zip files can still be build if desired:   https://github.com/Zimbra-Community/pgp-zimlet/wiki/Building-ZIP-for-use-with-zmzimletctl

**Comment by barrydegraaff** [comment]
Also I have been using the _dev version for over a year in production now. Testing the ZIP file only, for the release for pgp-zimlet-binaries repo.... is a lot of overhead for me.
