### ISSUE TITLE
can't add pgp public key from protonmail

### ISSUE THREAD

**Issue by ba1020** [Zimbra-Community/pgp-zimlet#140]
prob a protonmail error - key is not recognized ,no id no fingerprint etc

**Comment by barrydegraaff** [comment]
please copy-paste the message source, also pgp-zimlet ONLY reads public keys from plain/text messages.

**Comment by ba1020** [comment]
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v0.7.1
Comment: http://openpgpjs.org

xsBNBFS6vfQBCACL/FW0r0ZPFTMWRzf7rrKpeYFiJi6G8VnLWQuMy3a0mIwW
AQ47LF/Nz3XOJkhaSP979fNjsbhkMEUzKbrImdLufrCp9LirnGwbOTnlK56t
1W9/kAiFKGe+jzqsoq3a+3u11GzA170XvtT5oZHch+jaT2nHwMk4HE0P0Uvb
pwYDtGouPK04Yz/4ivkwNn9PkPZzwNkIsDVbniWKyjBYkcdcGCg7Ya0Pd7+t
tiT27GmH+q5IXi7/FawTqh7bNKmLHwifW3g5yMj74H99kiHdmxVpCX4x3DYn
6rx+Da2x9mW60MHX06JOD5kg9/wNk1JCfEjYJaaZgz8fU2+Tbw/yRfq3ABEB
AAHNBlVzZXJJRMLAcgQQAQgAJgUCVLq99gYLCQgHAwIJEDY7WhaQY9RlBBUI
AgoDFgIBAhsDAh4BAACI/Qf/QOnr+p09B5gva5rm/oUuKpKQtKgUACOwDc8D
NyHyhb1ieNhpXF90yUMCaPBJeaVlBIprpg8Ils/e0lc+ePsb+VmC52jydKUf
PAMIkOTTVzodtS82HR/GyTjAEAN5LPKefs99jskdw1Ujz89m0x2d8alVl0Jg
dH2qfXuOvyOVKWBwVDasfG3cgAskBd6HrJOq97QJdApt/15CUDktfgLqBgx7
ZcxWGpIZ0AA9PFNIdU1QRGh7rF3Jaqqsu+4Ip7pmg4C83/UUsk+FlZyNd+RC
foMOT+Lzfq8LjdoGNmw6PIrs9G2CKI4cvxaAeqKj477TXieSF1zODKTP+nNq
Oqrtqs7ATQRUur32AQf/W/7pssjNSesWQAYsSRIiHA4bkG0z3IWFGLOPkQ/4
TAVwrh/i5kHsYP3G7UOvFGVDBncAOkeouKYJ2yZvJ976eingFSRZSTx1fdQ7
cHHfp3IFkd8ylTkdSm7hoQznRDCd9QWhqWjpb7JDuD1KWM12fLALOPgh2zAO
j7qL6WdQmG/fv4aPQFV4mfDLJcHYjJ0mDdYxunVQMtuYKZMCqubdixhqqgmT
08iEhpMlJc8w2tBUwZoPziNSuD5eVtOmI+gpCMkiCX8rdU/ge23MV3FRXBEf
Dya77ahY3UZ6JEMuChIo3lSDvpaWKhcsdWgKS5PhY7+piFYmwqq3Y7gwAlPU
nwARAQABwsBfBBgBCAATBQJUur35CRA2O1oWkGPUZQIbDAAAFmQH/Rlz7C7N
oSqRubrd/pyrnKCXT5bAEJnUSe2DSOB2L/mkhv3sSFSsCHITVjmgGUzRTmAf
K5S9EMPGtVKjpZB/uBJXWohDWJ4ryBRh0cAd6at1qUF8Ixfl/JI2dtWq0kBx
Fx+gh3D1IKRjFdx3efCB4LbGH0q7FboRiLLrc8VApE3KOXtq2EoNL8loOe+Y
UHoJHXD+nSbkUypA02M+4yCsQL5TkBeK9lShJTB/tXVyFdZcQB1zLuecWA8q
QoEt1Qh9+/QTdsQTCHrr5umCPyfABSHVXzVsH/tYY0+06sZQH/QUpssMJNGr
62Gw1aCMDFH1pzlhfN3I0Tv5KtRKl8N95vQ=
=igE+
-----END PGP PUBLIC KEY BLOCK-----



this is my public pgp   protonmail key

**Comment by barrydegraaff** [comment]
It seems to work here, but the ID is indeed broken

• User ID[0]: UserID
• Fingerprint: 1b6e9c420eb4570b5d2836d5363b5a169063d465
• Primary key length: 2048
• Created: Sat Jan 17 2015 20:54:28 GMT+0100 (CET)

Maybe you (or the implementation) did not define one, or did so, on a different place.

PGP is complicated :-p

**Comment by barrydegraaff** [comment]
Fingerprint is fine though

**Comment by barrydegraaff** [comment]
Please alert protonmail, as they use an outdated version of OpenPGP.js https://github.com/Zimbra-Community/pgp-zimlet/commit/d24703a1d4b2f8d640919415eb9057cf3a6365fa

That has some vulnerabilities

**Comment by barrydegraaff** [comment]
Please generate a new key in protonmail, and check the version of OpenPGP.js in the generated key.

It should be > 1.3.0 as all the below has some vulnerabilities.

https://github.com/Zimbra-Community/pgp-zimlet/commit/d24703a1d4b2f8d640919415eb9057cf3a6365fa

**Comment by barrydegraaff** [comment]
running gpg --import <above key>
gpg: assuming bad signature from key 9063D465 due to an unknown critical bit
gpg: assuming bad signature from key 9063D465 due to an unknown critical bit
gpg: key 9063D465: no valid user IDs
gpg: this may be caused by a missing self-signature
gpg: Total number processed: 1
gpg:           w/o user IDs: 1

It looks like the problem is in your key. Not in pgp zimlet

**Comment by ba1020** [comment]
well this is the key they give me ............

and they say 

. Only incoming messages in inline OpenPGP format are currently supported.

**Comment by barrydegraaff** [comment]
I am not going to comment on that...

But if you have your private key, you can:
https://www.katescomment.com/how-to-add-additional-email-addresses-to-your-gpg-identity/

And then export a new public key with ID

**Comment by ba1020** [comment]
gpg> adduid
Need the secret key to do this.


well i don't have my private key from protonmail   grmbl 
dead end

**Comment by barrydegraaff** [comment]
If you don't have access to your own private key (while I can probably hack that out for you) I would abandon this service as the whole idea of pgp is that you are in control of your own keys.

And also looking at this public key, it does not look like that good of an implementation. No userID and all the above warnings, are NOT a good sign.
