### ISSUE TITLE
License changed from GNU GPLv3 to GNU GPLv2 (less restricted)

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/pgp-zimlet#141]
@evook
@latuannetnam
@maxxer
@metux
@oasiswork
@Openroadvietnam
@plobbesplobbes
@preachermanx
@rboufenghour
@travislee8964
@Veidit
@voretaq7
@YetOpen
@manens

Recently I changed the license for PGP Zimlet from GNU GPLv3, to GNU GPLv2, less restricted, but more importantly more compatible with upstream Zimbra.

You (may) have contributed a few lines of code under the old license, in case you object to this change, please update this issue, so we can remove your code.

Thanks, Barry

**Comment by barrydegraaff** [comment]
@plobbes

Recently I changed the license for PGP Zimlet from GNU GPLv3, to GNU GPLv2, less restricted, but more importantly more compatible with upstream Zimbra.

You (may) have contributed a few lines of code under the old license, in case you object to this change, please update this issue, so we can remove your code.

Thanks, Barry

**Comment by tuanta** [comment]
It's fine for me. Thanks!

**Comment by plobbes** [comment]
+1

**Comment by rboufenghour** [comment]
Ok for me . 

Cordialement, 
-- 
Redouane Boufenghour 
Chef de Projet messagerie 
StarXpert 
8, rue Eugène Varlin 
75010 PARIS 
Tél. : 01 75 57 84 82 
Fax : 09 72 11 78 40 


De: "Phil Pearl" <notifications@github.com> 
À: "Zimbra-Community/pgp-zimlet" <pgp-zimlet@noreply.github.com> 
Cc: "Redouane Boufenghour" <rboufenghour@starxpert.fr> 
Envoyé: Jeudi 17 Décembre 2015 04:50:44 
Objet: Re: [pgp-zimlet] License changed from GNU GPLv3 to GNU GPLv2 (less restricted) (#141) 



+1
