### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by ba1020** [Zimbra-Community/pgp-zimlet#142]

**Comment by ba1020** [comment]
Sidenote: enc to protonmail works even so their key is shit (noid etc)

**Comment by barrydegraaff** [comment]
We don't have one, only commits, but if there was a need for a changelog, I guess you should open an issue over at openpgpjs where the released dozens of releases lately without even commit texts

**Comment by ba1020** [comment]
this lazy snickerdoodles
