### ISSUE TITLE
Translations update for 2.0.0

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/pgp-zimlet#145]
Opening this ticket to keep track of translations that needs to be updated for the 2.0 release.

Currently, only up to date in english:
29
46
79
80

**Comment by barrydegraaff** [comment]
@maxxer please wait for my go-ahead for this update, lot more may follow

**Comment by barrydegraaff** [comment]
Add line 81, translations can start now!

**Comment by barrydegraaff** [comment]
For translators, how-to checkout,
make a fork of the code (via github website) then
git clone https://github.com/yourname-or-something/pgp-zimlet/
git checkout remotes/origin/openpgpjs-v2.0.0-dev
then change the code and test and
git commit
git push origin HEAD:openpgpjs-v2.0.0-dev
and then send a pull request (via github website)

**Comment by maxxer** [comment]
**CALL FOR TRANSLATION**

Barry prepared a new version of PGP Zimlet compatible with new upstream version of pgp js library.

There are some strings to update and a new one. The messages to update/translate are:
1. 29
1. 46
1. 79
1. 80
1. 81

**Warning**: the strings are in a separate branch *openpgpjs-v2.0.0-dev*. Please see [this post](https://github.com/Zimbra-Community/pgp-zimlet/issues/145#issuecomment-182917196) for instruction on how to check it out.

@travislee8964 @rboufenghour @tuanta @jorgedlcruz (others via email)

**Comment by barrydegraaff** [comment]
The openpgpjs-v2.0.0-dev branch has been merged with master, so you no longer need to use it.
