### ISSUE TITLE
Implement key generation with multiple id's (email addresses and aliases)

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/pgp-zimlet#146]
@tuanta Hello Tuan,

We are working on the 2.0 release, that features the new API from OpenPGP.js.

In 2.0 in the keypair generation dialog the field `User ID` gets replaced by: `Name` and `Email address`.

OpenPGP.js now supports generating keys with multiple User ID's. I suggest we allow the `Email address` field to contain a comma separated list of email addresses, all of them ending up in the generated key.

Can you add some code to parse the Email field and add it to:
tk_barrydegraaff_zimbra_openpgp.prototype.okBtnKeyPair

       var options = {
           userIds: [{ name:uidName, email:uidEmail }], // multiple user IDs (tuanta implement please)
           numBits: keyLength,                          // RSA key size
           passphrase: passphrase                       // protects the private key
       };

To checkout make a fork of the code:
git clone https://github.com/tuanta-or-something/pgp-zimlet/
git checkout remotes/origin/openpgpjs-v2.0.0-dev
then change the code and test and
git commit
git push origin HEAD:openpgpjs-v2.0.0-dev
and then send a pull request

Thanks for your work!

**Comment by tuanta** [comment]
@barrydegraaff  I am in a vacation for the Lunar New Year holidays.
I will try this hack once I come back to my home town today evening.

**Comment by barrydegraaff** [comment]
@tuanta when you are at it, you can use lang string 81 (display it between small tags under the `email ` field or so)

**Comment by tuanta** [comment]
I tried a hack to parse email addresses to generate an userIds array.
I checked the value in userIds options (an array). It's fine but the UserID in generated keys are _empty_
If you have time, can you see #149 and check together with me if what's wrong here.

**Comment by tuanta** [comment]
I fixed a typo in array then it works fine now.
Please check the pull request #150 .

**Comment by barrydegraaff** [comment]
Thanks, I confirm it works OK now, I have added some error handlers and strip spaces, if users type space in the comma separated list.

Also I automatically fetch the user aliases, and add them to the dialog. So all the users email addresses end up in the generated key.

Thanks Tuan!
