### ISSUE TITLE
support multiple private keys

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/pgp-zimlet#15]
Requested by a funder: support multiple private keys

**Comment by jahlives** [comment]
@barrydegraaff 
no way that this would be implemented? I found that your [fix here](https://github.com/Zimbra-Community/pgp-zimlet/issues/182) works perfect. The mails that still could not be decrypted are ecrypted using another pub key not beloning to the only private key that I can add to pgp-zimlet.
I would love the possibility to add multiple private keys. 
The use scenario is not even so uncommon ;-) Assume you have a mailserver that collects your multiple external accounts which contain already encrpted mails using. Nowadays more and more providers start adding the possibility for the end-user to add public keys so mails received on the providers systems get encrypted before written to the mailbox.

**Comment by barrydegraaff** [comment]
@jahlives every now and then this comes up, while it is doable, doing it in a way that beginning users can comprehend is difficult, as pgp zimlet is meant to be the easiest solution for `normal` users. Powerusers tend to go with Enigmail anyway.

I am working on supporting Yubikey4 to mitigate this also.

In any way it would take a considerate amount of time, and I would need more funding for this one,

**Comment by jahlives** [comment]
I know it's not much but I just donated something for your project

**Comment by jahlives** [comment]
@barrydegraaff 
saw today the latest release from Roundcube. It supports pgp, especially multiple private keys, via enigma plugin. Do you think that such thing could be implemented in the zimlet? Or is it technically not possible? The pgp support for multiple private keys is the only thing that prevents me from switching entierly to zimbra (for the webmail at least)

**Comment by barrydegraaff** [comment]
Its doable, and would be a select list instead of textarea in case your key is in the cache. But it is not on the top of my to-do list right now.

I will be adding https://github.com/barrydegraaff/emailjs-mime-parser  and that will make pgp-zimlet able to parse all mime inside pgp/mime messages

I need to make the features that we have right now, good, before adding more new features. 

Please be patient, since you donated I probably add this in the coming weeks.

**Comment by barrydegraaff** [comment]
One can export multiple private keys in a single armored block:
gpg2 --export-secret-keys --armor ID1 ID2 and so on

The Zimlet should then also allow storing multiple passwords and offer a selection on what key to use on signing... so that would still be some work.

We can off course also provide multiple inputs for private keys, but it is a bit scary for new users.

**Comment by barrydegraaff** [comment]
It seems merging private keys is a feature added in GnuPG 2.1 but for some reason there is no documentation on how to do it.

Also it can be done in older versions:
http://security.stackexchange.com/questions/32935/migrating-gpg-master-keys-as-subkeys-to-new-master-key

But it seems a bit complicated.

**Comment by barrydegraaff** [comment]
@jahlives some support for multiple private keys is added to the version currently in git, you can test it now, see: https://github.com/Zimbra-Community/pgp-zimlet/wiki/Install-from-git  and skip the line that starts with [root@myzimbra pgp-zimlet]# git checkout... as you need to test this in the unreleased version.

https://github.com/Zimbra-Community/pgp-zimlet/wiki/Multiple-private-keys

You can also wait for the next version to be released, it will be < 1 week/

**Comment by jahlives** [comment]
@barrydegraaff 
works as charme, thanks a lot for your efforts :-)
Just one thing if I might, although it's not a big problem but a "would be nice to have feature": would it be possible to chose the correct private key not only via the number in the armored file but also via the emailaddress that is used as identity? Or even try an automatic decryption based on recipients address and the address used as identity for the key in gpg?

**Comment by barrydegraaff** [comment]
Yes, but I think that will go to next years dev. sprint :-p

**Comment by barrydegraaff** [comment]
related issue: https://github.com/openpgpjs/openpgpjs/issues/466
