### ISSUE TITLE
Encrypt & Sign Buttons not displaying in Compose window

### ISSUE THREAD

**Issue by bobm3483** [Zimbra-Community/pgp-zimlet#159]
Guys - 

I really like what you have done, both with the GPGP zimlet and the other zimlets you have done... I'll be loading your sticky notes and follow-up zimlets shortly, however right now I have an issue w the GPGP zimlet in the the Encrtypt & Sign buttons do not display in the compose window.

Zimbra 8.6, Umb 12.04, Chrome Version 49.0.2623.110 m
GPGP installed from Git.
Also FYI the zimlet does not show in the Zimbra Admin Zimlets list (due to install in _dev? Why??)
Please advise
bobm
bobm@windward-dev.com

**Comment by barrydegraaff** [comment]
Hello Bob,

Do you happen to compose in a new window? That is not supported (bug in Zimbra) the buttons only show when composing in a new tab (see Preferences -> mail -> uncheck Always compose in new window.)

Also the zimlet does not show in the admin ui, that is correct, and one disadvantage of installing in _dev, but the _dev solves a lot of cache issues, so.

**Comment by bobm3483** [comment]
Barry - Thanks for the quick response..

I actually JUST realised the issue with compose in new window vs a compose tab(never used it like that.. but kinda like it as I start Zimbra in a dedicated window app) and was about to send you a msg saying sorry for being dumb...

PS - are you talking with Adam Cody @ Zextras (formerly of Zimbra) ?
Sounds like things may be looking up..

bobm

PS - will load some of you other zimlets soon, keep up the good work

**Comment by bobm3483** [comment]
ps - would a ln -s _dev/gpgpzimlet gpgpzimlet 
work/solve both issues?
just a thought

**Comment by bobm3483** [comment]
pss - one last question

Why exactly can't the HTML version of the message be encrypted?
I understand that a txt only msg body is simpler to work with... but is there a tech reason??

thx again...
bobm

**Comment by barrydegraaff** [comment]
- Yes I talk to Adam all the time, we are both on the Zeta Alliance.

- ln -s, dunno, haven't tested

- Sending html email would require Zimbra to support pgp/mime and despite some effort, it has not been added to the server see: https://bugzilla.zimbra.com/show_bug.cgi?id=100883

Receiving html messages would be easier, it is just not used that often in orther clients (like enigmail) it is not recommended and is a lot less secure in terms of XSS attacks, so, I won't be chasing that feature no more. Unless someone funds it especially.

Thanks for all the compliments, of course you can make donations via:

PayPal: info@barrydegraaff.tk
Bank transfer: IBAN NL55ABNA0623226413 ; BIC ABNANL2A

**Comment by barrydegraaff** [comment]
also, receiving html in pgp/mime messages should be displayed as text by pgp-zimlet, but it is not our best feature :-p

**Comment by bobm3483** [comment]
Barry - 

Sorry, but... reviewing the User Doc 

IN the case of Thunderbird->Zimbra the error: De-crypted msg not signed 
the doc describes the problem and the fingerprint... but does not describe a solution... 

...describe the 'with sign' option on Thunderbird.... or what is best practice?? 

bobm

**Comment by barrydegraaff** [comment]
`Decrypted message not signed` is not an error message, it (should) tell you that the message you just decrypted was NOT signed with pgp by the sender... maybe there is a bug, does thunderbird verify the signature as OK?
