### ISSUE TITLE
zimbraZimletUserProperties value length(93012) larger than max allowed: 5120

### ISSUE THREAD

**Issue by jvaubourg** [Zimbra-Community/pgp-zimlet#160]
> zimbraZimletUserProperties value length(93012) larger than max allowed: 5120

5120 chars for a public key is not enough. Public keys with 4096 bits should be supported, because this is now a standard for a lot of people.

**Comment by barrydegraaff** [comment]
This is actually a FAQ, and to solve is in the readme:
https://github.com/Zimbra-Community/pgp-zimlet#an-unknown-error-accountinvalid_attr_value-has-occurred

Also in 8.7 the value is allowed to be larger, alternatively you can store public keys in the notes fields from your contacts, see the built in help. Or http://barrydegraaff.github.io/help/#contacts-scanning
Regards, Barry
