### ISSUE TITLE
No history when responding

### ISSUE THREAD

**Issue by jvaubourg** [Zimbra-Community/pgp-zimlet#161]
When we respond to a encrypted message (decrypted thanks to pgp-zimlet), the previous message is not quoted in the body of the response. Is there a way to improve that?

**Comment by barrydegraaff** [comment]
Its annoying indeed, but fixing it will be complicated.

Probably have to do something with ComposeController, but not sure if Zimlet API covers that. Alternatively storing the message unencrypted on te server (not going to do that). I'll take some time to  think about other solutions this week.

**Comment by barrydegraaff** [comment]
One way would be adding a Reply button, just like the print button.

**Comment by barrydegraaff** [comment]
Added reply/reply-all buttons to PGP Zimlet

https://github.com/Zimbra-Community/pgp-zimlet/commit/a4374f17fff1eebbaefea00969c237f1bb9361a8

Maybe you can test and verify this patch.

Follow the install howto from here:
https://github.com/Zimbra-Community/pgp-zimlet#install-zimbra-openpgp-zimlet
But skip the checkout line : 'git checkout 2.0.7'

You should then have the latest version.

**Comment by barrydegraaff** [comment]
fixed in the next release

**Comment by jvaubourg** [comment]
Sorry for not replying sooner, but thank you for your prompt response!

I try this as soon as possible :).
