### ISSUE TITLE
PGP is malfunctioning

### ISSUE THREAD

**Issue by imonserrat73** [Zimbra-Community/pgp-zimlet#167]
I have installed the pgp zimlet in ZCO 8.6.  I can send and receive mails for the first time, but when I try to read another mail for second time pops up a message "Decryption Failed" and it says that the private key and the passphrase are wrong, but I haven´t made any kind of changes.  It happens in all web navigators (chrome, firefox, IE and so on).
Please help me!

![pgpproblem](https://cloud.githubusercontent.com/assets/18620043/14751289/c560eaac-088e-11e6-839b-db2623e038cb.png)

**Comment by barrydegraaff** [comment]
Well I did not test the network edition for some releases or ZCO (ever).

Can you try again by adding ?dev=1 in the addressbar (url) of your Zimbra
https://...fin.ec/?dev=1

If that does not work, did it work in the previous version:
https://github.com/Zimbra-Community/pgp-zimlet/blob/stable/README.md
But use
**git checkout 2.2.1** 

If that also does not work, please provide me with an account to debug, you can send login details to info@barrydegraaff.tk

**Comment by barrydegraaff** [comment]
Also make sure you have used the correct public key.

**Comment by imonserrat73** [comment]
Thank you for your collaboration, it worked! I got one more question: Can it be used for safari or it doesn´t matter the web navigator type?

**Comment by barrydegraaff** [comment]
Safari should work!

https://saucelabs.com/u/openpgpjs

**Comment by imonserrat73** [comment]
Thank you Barry,
One more question: is it possible to create a COS and establish it there? I don´t want that everyone have this zimlet in their browser.

**Comment by barrydegraaff** [comment]
with: 
https://github.com/Zimbra-Community/pgp-zimlet/wiki/Building-ZIP-for-use-with-zmzimletctl

**Comment by tuanta** [comment]
>  One more question: is it possible to create a COS and establish it there? I don´t want that everyone have this zimlet in their browser.

Yes, you can enable/disable every single zimlet for each user (in user profile) or CoS (create a new CoS or use an existing one)
