### ISSUE TITLE
Zimlet version 2.3.7 "hangs" upon decryption

### ISSUE THREAD

**Issue by jahlives** [Zimbra-Community/pgp-zimlet#182]
I have an issue with the zimlet in version 2.3.7 on Zimbra 8.6 running on Centos 6.7 (64bit). My Zimbra receives encrypted messages from my smtp frontends. Any other client can decrypt them perfectly like for example thunderbid+enigmail or evolution. 
If I try to decrypt such messages with the pgp-zimlet it asks for private key and password and then hangs forever showing the "I do something or maybe not" icon" ;-) No error message. If I feed the encrypted content directly to gpg -d it decrypts it without any problem. 
Is there a way to find out where pgp-zimlet hangs? Any logfile or debug mode?

**Comment by barrydegraaff** [comment]
Try Google Chrome... 

This problem occurs when:
You use DSA keys and or 
use Internet Explorer and pgp/mime or
use message > 6 MB or so.. depending on your pc

**Comment by barrydegraaff** [comment]
Firefox is also a bit slow at times, also native code... aka just running a binary on top of the os (enigmail) is always faster than javascript. Just to keep it in mind.

**Comment by barrydegraaff** [comment]
dsa keys are usually old keys, aka generated over 5 years ago.

**Comment by jahlives** [comment]
Sorry forgot to mention that I already use chrome :-) Running on Fedora 23
I do not use DSA keys but RSA and the message is quite small, roughly 2K

**Comment by barrydegraaff** [comment]
Well, then it should not happen, try reloading your screen and maybe send one of your problematic messages to to barrydg@zetalliance.org (PGP fingerprint: 9e0e165f06b365ee1e47683e20f37303c20703f8) so I can look into it

**Comment by barrydegraaff** [comment]
Also congrats, I am also in F23 and chrome... the Zimlet hangs here once a week, but I do test edge cases :-p

**Comment by jahlives** [comment]
When I reload then the mailbox loads properly again. But after clicking on such encrypted messge the zimlet hangs again. Is it important to mention that the message is not signed just encrypted? For me it looks like the zimlet ends in some kind of a loop while parsing the mail. I can send you test samples of the mail(s) but just for the headers. For the content you would need access to my private key and thats no-go for me, no offence ;-) I tested as well with firefox, same result as chrome

**Comment by barrydegraaff** [comment]
Well headers wont help, can you send a new mail, that has the same problem? Aka without confidential text, but copy paste lorem ipsum or so into it?

**Comment by jahlives** [comment]
I just dropped you a mail :-)

**Comment by barrydegraaff** [comment]
@jahlives can you point me to the documentation to the sieve filter that you use to create the message. I would like to support your use case, but rather work against known setups. Otherwise there are too many options to implement. 

At this time it looks like your pgp/mime message is formatted in a way this zimlet does not yet support, I added test case: https://github.com/Zimbra-Community/pgp-zimlet/commit/a5daa6b40cf0779d3b1da1668034ea0bc04edfaf

**Comment by barrydegraaff** [comment]
The Zimlet support the following:
Content-Disposition: attachment, will be treated as attachment
The following content types:
*text/plain* is treated as text body
*text/html* is treated as text body

Your solution does:
Content-Type: application/octet-stream
Content-Disposition: inline

And that is not yet implemented, I will have to look into some rfc on that...

**Comment by jahlives** [comment]
@barrydegraaff 
the program I use to create this messages is [gpgit](https://gitlab.com/mikecardwell/gpgit), a perl script from Mike Cardwell. This program is called on my mailboxserver via a sieve script to encrypt the message.

**Comment by barrydegraaff** [comment]
@jahlives thanks for reporting.

Support for your setup is added in the next version, if you could, please test the new version by following:
https://github.com/Zimbra-Community/pgp-zimlet/wiki/Install-from-git

And please **skip**  the line that reads 
git checkout 2.3....

Then it should work. A test case for pgpit will be added to our test script.

Barry

**Comment by jahlives** [comment]
@barrydegraaff 
thanks a lot for your fix. Although it does not work for all mails in my case. It's very odd for me but some mails I can decrypt now and others not. Weird ... For me it seems that its somehow content related?

**Comment by barrydegraaff** [comment]
@jahlives can you do me a favor and send the lorem ipsum test message again using this keypair:
https://raw.githubusercontent.com/Zimbra-Community/pgp-zimlet/stable/test/thunderbird-engimail-test-keypair.txt

This helps me to keep testing easy.

In the mean time, you can put the word `debug` without quotes in the public key 30 field, this way, the zimlet should put the decrypted text in the mail view, in a textarea.

The problem with pgp/mime is that there are 100 ways of doing the same thing, and right now, a good mime library that is suitable for this project is not yet available in JavaScript, that is why I have to code most of it myself. So please send me te above test case again, and for each message that does not work, we have to repeat the process.

Its the price of being the first users of pgpit and zimlet combo.
Barry

**Comment by jahlives** [comment]
@barrydegraaff 
sent you the testmail directly and on your test account on my server

**Comment by barrydegraaff** [comment]
Thanks, pgpit test case added
https://github.com/Zimbra-Community/pgp-zimlet/commit/6e008d47dad2dbb39a30562896bc7b5ce02f871f

**Comment by barrydegraaff** [comment]
I did some unification, so the zimlet should support your use case even better, update from git or wait for the next release.
