### ISSUE TITLE
support multiple-keys in a single armored pgp public key block

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/pgp-zimlet#184]
when exporting from enigmail key management a selection of keys, they end up in a single armored pgp public key block.

But the zimlet only support 1 key per armored block

**Comment by jahlives** [comment]
@barrydegraaff 
I tried with the latest version like described here: https://github.com/Zimbra-Community/pgp-zimlet/wiki/Install-from-git
Exported several private key into one armored block. But neither add it directly into pgp-zimlet nor add it into the notes of my contact does work for me

**Comment by barrydegraaff** [comment]
Did you check `Scan contacts` in the manage key window?

**Comment by jahlives** [comment]
yep I did check the box. It only works for the key that is entered in the pgp-zimlet private key section, but no for the contact of myself (with 3 keys in notes)

**Comment by barrydegraaff** [comment]
send me the public keyblock please, you can copy-paste here as well

**Comment by jahlives** [comment]
ups I think I missunderstood something :-) I thought the feature was for multiple private keys in one armored block. Should learn to read better, sorry ;-)

**Comment by barrydegraaff** [comment]
That is another issue, its next on the to-do list, it will work similar, but have yet to figure out a way to store the multiple passwords and how to keep that simple in the UI.
