### ISSUE TITLE
 ***UNCHECKED*** gets added to the subject.

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/pgp-zimlet#193]
***UNCHECKED*** is added by Zimbra AS/AV, it means the anti-virus and spam assassin could not read the encrypted message.

Not sure if the user understands what is UNCHECKED, so can we remove that from the subject line?

**Comment by tuanta** [comment]
I think we can change this in Amavisd configuration.

**Comment by barrydegraaff** [comment]
Looking here:
http://akiramtech.blogspot.nl/2015/11/zimbra-added-unchecked-in-mail-subject.html

      su to the root.
      root# cd /opt/zimbra/amavisd/sbin/
      root# cp -pr amavisd amavisd.org
      root# vi amavisd
      
      change the line like the following.
      $undecipherable_subject_tag = '***UNCHECKED*** ';
       to
      $undecipherable_subject_tag = '';
      then restart amavisd:
      root# su - zimbra 
      zimbra$ zmamavisdctl restart

Now need someone to confirm this, and then we can put it in the wiki

**Comment by tuanta** [comment]
It should be fine. You need to try it on a test system (I have nothing here).

Btw, do you think it's best to replaced to things like "ENCRYPTED" instead of _blank.

**Comment by barrydegraaff** [comment]
I can confirm the above steps work, and I will put it in the install readme.

**Comment by barrydegraaff** [comment]
I think adding stuff to the subject is ugly, users don't get it, and most people will just be annoyed.

**Comment by barrydegraaff** [comment]
There has been a HUGE traffic increase on this issue, maybe you want to take a look at:

https://blog.zimbra.com/2016/10/clamav-v0-97-included-zcs-8-0-6-tags-messages-unchecked/
