### ISSUE TITLE
Cannot send public key to the server if the Name field contents the space

### ISSUE THREAD

**Issue by DenisOGutskalov** [Zimbra-Community/pgp-zimlet#199]
Hello, 
i figured out that when i generate key pair with Name like: Name Surname, than zimlet cannot send it to the key server. If the name is composed of single word it works correctly. Also it works correctly when i generate key pair with Name in quotes, like that: 'Name Surname'. I'm sorry i'm not a programmer and i cant find where is to fix it.

**Comment by barrydegraaff** [comment]
Thanks for reporting, I think it has only been tested with quotes around the name, I will fix this in a few hours.

**Comment by barrydegraaff** [comment]
I just tested this, and it works fine... maybe you have been seeing a temporary network issue.

As keyservers are not always available

**Comment by DenisOGutskalov** [comment]
Thank you, i use our company's local keyserver and I see this issue within 3 days at least

**Comment by barrydegraaff** [comment]
I have not been able to reproduce this, I generated this one:

https://sks-keyservers.net/pks/lookup?op=vindex&search=testerapp%40test.com

using:

![2016-06-09-132743_3840x1080_scrot](https://cloud.githubusercontent.com/assets/4353213/15928226/fc29e5b6-2e45-11e6-8dc9-f8eb36b57a57.png)

**Comment by barrydegraaff** [comment]
without using quotes

**Comment by DenisOGutskalov** [comment]
Yes, i've upgraded to the 2.5.6 version now and it works good. Thank you!
