### ISSUE TITLE
Decode ascii armored attachments?

### ISSUE THREAD

**Issue by leed71** [Zimbra-Community/pgp-zimlet#204]
Hi

Sorry if I've missed something but does the zimlet do ascii armored attachments?
I never get the "decrypt" option with these?

Many thanks
Lee

```
------=_MIME_BOUNDARY_000_17163
Content-Type: text/plain

This is a test mailing
------=_MIME_BOUNDARY_000_17163
Content-Type: application/octet-stream; name="test.asc"
Content-Description: test.asc
Content-Disposition: attachment; filename="test.asc"
Content-Transfer-Encoding: BASE64

LS0tLS1CRUdJTiBQR1AgTUVTU0FHRS0tLS0tCkNvbW1lbnQ6IEdQR1Rvb2xzIC0gaHR0cHM6Ly9n
cGd0b29scy5vcmcKCmhRSU1BMEExa0hLY3JyRlZBUS8vWitVdkdqRDJIV3J5U0o1ZVI3bGgwMVlK
TVNLTmtKOWFWM1hUV3BpSTVFK0QKREdUYUw2WTMzUCtJRDdNd01kL2hXUFE5c25DTk5TOGtCTFVN
Q2hZTVF6MzEvanU5QmVlYzRFKy9Ca1c5R1ZCUApuRmNNUC9KQWREcG9TcHhXeUpwUmxQZ1dsS3Z0
MG9KMEsrWHlXUXMxUllpR0dVc0JDTUtJbzQxVXVJN0lETDFFCnJWazhWZ3pPc3VBRzZsU25pVGZi
ckZVeTl0OWp2SGVjVFpWY2VESk9KVThSWml2NURaRlVKSWlpbHdLVVZKakMKbmdJcHJ3bDlJYndM
TmJwNjF1dEszVytKRG5UcmhJcnQ1ZnpiL2srR2hDclNxTUg3MHF0STZTTXNialF1azNCZAoxbkVx
NU9QRnlkbFF5aThzbDZKM2RjQlF1MUF0U21COWxUbDk3Y3B3YW04b3Y1M0k2SVFkTnpsRE5hUzY0
QUdmCnE4bHlncThrVU1JRXNac2hCTWZmT3BWQlpuQ0J3d1BhL3NQVjQwOUNuRWZqcWtjYzlmbytD
ZlgzeHc0TlF5SXkKUGNMZ3VoNXZLbHVvSUhXMk1yNTk4YlRGNjNwZ0xVK3Zidk82OFl6Y1krWnM0
QkoxOXpvUXBOYVpFNEpOcERCZgo4YTZ0T2lEdzdhUFM5QXkyUTAwVEJZS1BmWUtJdlYvekR5ODNa
cUJyWnNNTUJwa1h4QTJDUU1IOHRLUFoyQ2ZYCnNvRlpsNTNnZFdhWFRObkhJRWtyZUExdXR6MEJo
NVBhVEpjS1hzY2U2aFhYTnFVR1ZDL0UxZmg4ZWNNL2UrSk0KMXhUN1FSL0xkZThyR1FUc1JuWmhR
Y3VwTDU4eXVpb09xS2tLSitPUkJJRWV2a0h0eEtkUHhaK2JtT2NHaE96UwpSUUc1NmlmZ2JKQy9U
NDFGZGhQb0s2dE9YaWF6UnZWUWNoVjNWeC93STBjNVpIUGZaY3RoTytoR1Y4VFlTaktJCjdKYkZZ
UUdKMTZPNkV2MW8vMzhRYUZBZmFaRkh3Zz09Cj1rdGtDCi0tLS0tRU5EIFBHUCBNRVNTQUdFLS0t
LS0K

------=_MIME_BOUNDARY_000_17163--
```

**Comment by barrydegraaff** [comment]
Hello leed71,

Thanks for reporting, this is fixed in https://github.com/Zimbra-Community/pgp-zimlet/commit/6ff4b3549c280d235751b824f1e16ecb0abb120f

What you do is according to the PGP/MIME RFC, an unfortunate side effect is that this zimlet will now show the decrypt link for all application/octet-stream type attachments, and these may or may not be PGP. Anyways, if you can test using the version from git and report back to me if it works, that be most appreciated.

Follow the install steps:
https://github.com/Zimbra-Community/pgp-zimlet/wiki/Install-from-git

But skip the line that says: 'git checkout...' as you need the lastest version from git to test.

Thanks, Barry

**Comment by barrydegraaff** [comment]
@leed71 can you send a test message with an example attachment as above to barrydg@zetalliance.org using the publickey:
https://raw.githubusercontent.com/Zimbra-Community/pgp-zimlet/stable/test/thunderbird-engimail-test-keypair.txt

Also what email client do you use?

Thanks!

**Comment by barrydegraaff** [comment]
Looking at the code behind the decrypt link, it all requires binary data, aka it does NOT work for your use case. So it needs some work, and I would need that test messages to look into it.

**Comment by leed71** [comment]
Hi Barry

Thanks for the timely response. I have sent an ascii armored attachment to your address using that key.

For the tests I'm using swaks to send the mail, but in real life its a java program. I've checked and the message is the same from both with regard to the attachment.

Thanks again for your help.

**Comment by barrydegraaff** [comment]
Thanks, I will look into it tomorrow, in the mean time maybe you can use pgp/mime as this would work-around this issue. It may not be that hard, and also may prevent some other issues further down the road.

**Comment by barrydegraaff** [comment]
@leed71 this bug is now fixed, please help us by testing it:

Follow the install steps:
https://github.com/Zimbra-Community/pgp-zimlet/wiki/Install-from-git

But skip the line that says: 'git checkout...' as you need the lastest version from git to test.

Thanks, Barry

**Comment by leed71** [comment]
Fantastic, works perfectly :)

Thanks
