### ISSUE TITLE
pgp-zimlet changing keyserver to local gpg server is not working

### ISSUE THREAD

**Issue by aydintd** [Zimbra-Community/pgp-zimlet#205]
Hello,

I'm running Zimbra 8.6.0_GA_1153 version on Ubuntu 14.04 LTS smoothly. I installed the gpg-zimlet as described in README.md of the project (which comes with the version 2.5.8)

I also have a local GPG server which can be reached from zimbra and running sks daemon which versions is 1.1.4-2.1ubuntu1 installed from ubuntu official package repository and apache2 proxying with HTTPS. It just works just fine (importing or exporting local gpg keys etc.) we can use the local gpg server from our web browsers like https://keyserver.pardus.org.tr also without any problems.

I just want to use our local gpg keyserver because we dont have Internet access on our Zimbra network and I want to provide gpg support on e-mails for my clients.

Before deploying the zimlet, I unzipped the whole gpg-zimlet zip directory, found the config_template.xml file and changed the https://sks-keyservers.net domain to point out our domain which is https://keyserver.pardus.org.tr and i re-zipped the zimlet and deployed as zimbra user with

_$ zmzimletctl deploy tk_barrydegraaff_zimbra_openpgp.zip_ and it seems deployed fine.
after i restart whole zimbra systems with _$zmcontrol restart_ and after all these I could see our keyserver definition in zimlet keyserver lookup page and submit to keyserver pages on Zimbra.

But when I try to query someone's gpg key, it throws an exception as "0 undefined" and also when I try to submit my gpg public key (which generated from zimlet) It throws the same exception.

Here I attach 2 screenshots about the issue when I try to submit my public key and a query gpg key on our local gpg keyserver.

Here I dont have any ideas what I am doing wrong or what's the problem,

Thank you all

![zimlet-gpg-query](https://cloud.githubusercontent.com/assets/1241083/16342287/f576df08-3a39-11e6-8e07-e8754f30e5b5.png)
![zimlet-gpg-submit](https://cloud.githubusercontent.com/assets/1241083/16342286/f5765f6a-3a39-11e6-82ac-41df347499a2.png)

**Comment by barrydegraaff** [comment]
Hello,
0 undefined, means the keyserver did not return a response to the user running the zimlet.

If you are sure the user can query the keyserver.. most likely there are security settings on your keyserver, preventing the zimlet from accessing it.

Most likely your keyserver does NOT support CORS, that is Javascript cross-domain requests, you probably need to inject the header on the keyserver:
http://enable-cors.org/server.html
OR
use zimbra-nginx to reverse-proxy your keyserver, see https://wiki.zimbra.com/wiki/Zimbra_Proxy_Manual:Adding_Additional_Reverse_Proxy_To_Zimbra_Proxy

You will also have to configure pgp zimlet to use: https://yourzimbraserver.com/keyserver

where proxy-location points to your keyserver via nginx:

`  location /keyserver/ {
     proxy_pass https://keyserver.example.com/sks-path/;
  }`

**Comment by aydintd** [comment]
Hello,

I enabled the header module on apache web server and added the _Header set Access-Control-Allow-Origin "*"_ to my <VirtualHost *:443> definition on my key server. After restarting the service now I can query all gpg's and import gpg's to my local GPG server!

I appreciate your helps. Problem solved.

**Comment by barrydegraaff** [comment]
I am re-opening this, as it needs to be added to the wiki.
