### ISSUE TITLE
Decrypt problem when first encrypt and second sign

### ISSUE THREAD

**Issue by maximdogonov** [Zimbra-Community/pgp-zimlet#206]
Hi! 

When I create new mail type some text. 
Then first press encrypt and second sign. Zimbra can't decrypt this messages. 

![zimlet_pgp](https://cloud.githubusercontent.com/assets/12844960/16565281/55e5f92e-421d-11e6-9573-5e9d32b53ac4.png)

**Comment by barrydegraaff** [comment]
You should use only the encrypt OR sign button and NOT combine the two.

If you want to just sign, hit the sign button,

if you want to encrypt and sign, hit the encrypt button and make sure your private key and passphrase are shown in the encrypt dialog. This will sign the encrypted message. 

See: http://barrydegraaff.github.io/help/2-encrypt-dialog.png
The part under `Optional: Sign your encrypted message...`
