### ISSUE TITLE
OSX Safari has not been tested in over a year, need hardware or VM for testing

### ISSUE THREAD

**Issue by maximdogonov** [Zimbra-Community/pgp-zimlet#207]
Hi!

When I try encrypt attach file with file size 1Mb I wait 15 minute and nothing.

**Comment by barrydegraaff** [comment]
Try it again from Google Chrome?!

**Comment by maximdogonov** [comment]
What about Safari?

**Comment by maximdogonov** [comment]
what about Firefox?

**Comment by barrydegraaff** [comment]
Firefox is pretty slow

**Comment by barrydegraaff** [comment]
Safari, I havent tested it in over a year, as I no longer have access to any mac system... so maybe it is borken.

Maybe you can see if it works on Chrome on OSX...

**Comment by maximdogonov** [comment]
Ok, I try on Chrome on OS X

**Comment by maximdogonov** [comment]
I try it. 
it works on Chrome on OS X.
But on Safary on OS X doesn't work.

**Comment by maximdogonov** [comment]
![img_06072016_142912](https://cloud.githubusercontent.com/assets/12844960/16616485/98fbd48c-438e-11e6-8181-50f87197c6dd.png)

On Windows Chrome same problem.

**Comment by barrydegraaff** [comment]
Updated the readme to show Zimbra OpenPGP Zimlet works on OSX with Google Chrome.

Since Safari no longer works on Windows and my last OSX machine died, I will need someone to bring me a working OSX KVM image, so I can test via a virtual machine or someone has to donate some Apple hardware so I can test with that.

Until that is resolved, there probably will no longer be Safari support. Anyone?

**Comment by barrydegraaff** [comment]
In reply on the Windows comment, if you still have troubles, maybe you are using a DSA key... or some other key that was not generated with OpenPGP.js that does not work well. 

Does attachment encryption work with keys generated with this Zimlet?

**Comment by maximdogonov** [comment]
We generate key use always Zimlet tools (OpenPGP.js)

**Comment by maximdogonov** [comment]
Now we double check it

**Comment by maximdogonov** [comment]
Ok, on Windows Server 2008R2 64bit on Chrome problem. And now we take Windows 7 64 bit and Chrome all work fine.

**Comment by barrydegraaff** [comment]
We need to apply for a license here for testing:

https://www.browserstack.com/pricing

**Comment by maxxer** [comment]
Maybe a [VM](http://techsviewer.com/how-to-install-mac-os-x-el-capitan-on-vmware-on-pc/) could do?

**Comment by barrydegraaff** [comment]
yes if you can set one up that runs on Fedora, please let me know.\

So far I have not seen a doable solution for that. Also my graphics card sucks,
so I am pretty sure running a MAC VM on KVM on my system would be a no-go.

**Comment by maxxer** [comment]
> yes if you can set one up that runs on Fedora, please let me know.\

I did that on Ubuntu + VirtualBox. I've used it for really short, like minutes, so can't say about performances. If you want I will look for the howto

**Comment by barrydegraaff** [comment]
Can you send me the image, not the how-to as am am already time poor :-p

**Comment by barrydegraaff** [comment]
That actually worked, its also the very first time I have seen that working on linux, great! Thanks!

**Comment by barrydegraaff** [comment]
Off course cannot run KVM and VirtualBox at the same time on the same machine... but I can work around that

**Comment by barrydegraaff** [comment]
A 180kb file worked ok

**Comment by barrydegraaff** [comment]
A 1,3 MB file worked as well, and is also quite fast.

@maximdogonov sorry it took so long, maybe you can try and use a different public key? I tried with a 4096 rsa one and it was done in a few seconds.I cannot confirm your issue. However, i found another one.
