### ISSUE TITLE
Multiple COS issue

### ISSUE THREAD

**Issue by sempiterna** [Zimbra-Community/pgp-zimlet#213]
The pgp zimlet works on only one COS. I have two active Classes of Service. One one of the COS-es, the zimlet does not work. It shows up in the zimlets list in the web client, but does not have an icon in front of it. Right clicking it shows the menu items, but they have no effect. It does work on my other COS where most of my domains reside under.

Maybe it is related to another issue, where the "Please verify the fingerprint" link in the "Import public key" popup fails because it wants to find the tk_barrydegraaff_zimbra_openpgp directory in /opt/zimbra/zimlets-deployed/_dev instead of /opt/zimbra/zimlets-deployed/. 

I tried to solve it by creating a symlink of tk_barrydegraaff_zimbra_openpgp inside the _dev directory. Which makes it work in the COS which has the issue, but breaks it in the other COS, which then sees two instances of the same zimlet.

**Comment by barrydegraaff** [comment]
please try:

https://github.com/Zimbra-Community/pgp-zimlet/wiki/Install-via-zmzimletctl

**Comment by sempiterna** [comment]
That works, but still leaves the issue where the "Please verify the fingerprint" link in the "Import public key" popup (when someone sends you a public key) fails because it wants to find the tk_barrydegraaff_zimbra_openpgp directory in /opt/zimbra/zimlets-deployed/_dev instead of /opt/zimbra/zimlets-deployed/.

**Comment by sempiterna** [comment]
It's hardcoded in the language files: 

74 = Do you wish to import this public key? Please <a target="_blank" href="/service/zimlet/_dev/tk_barrydegraaff_zimbra_openpgp/help/index.html#fingerprint">verify the fingerprint</a>.

**Comment by barrydegraaff** [comment]
yap, that's a bug... will fix later this week.

**Comment by barrydegraaff** [comment]
New version added that fixes this, new help page added.
