### ISSUE TITLE
Encryption attachment

### ISSUE THREAD

**Issue by StaLeWaR** [Zimbra-Community/pgp-zimlet#214]
Zimbra OpenPGP Zimlet Version: 2.6.8
In addition attachments in the name of which has Cyrillic characters freezes zimlet

**Comment by barrydegraaff** [comment]
**Confirmed**

Uncaught (in promise) DOMException: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'attachment; filename="АВГДЄЗИѲ.txt.pgp"' is not a valid HTTP header field value.
    at https://powermail.nu/service/zimlet/_dev/tk_barrydegraaff_zimbra_openpgp/tk…ff_zimbra_openpgp.js?v=161025050454&language=en&country=GB&debug=1:2766:26
(anonymous) @ tk_barrydegraaff_zimbra_openpgp.js?v=161025050454&language=en&country=GB&debug=1:2766

req.setRequestHeader("Content-Disposition", 'attachment; filename="'+ file.name + '.pgp"');

**Comment by barrydegraaff** [comment]
http://stackoverflow.com/questions/34670413/regexp-to-validate-a-http-header-value

Seems like legacy standards crap

**Comment by barrydegraaff** [comment]
This is fixed in the 2.6.9 release, thanks for reporting
