### ISSUE TITLE
Getting an "this.handlerObject._int" error when users login to zimbra 

### ISSUE THREAD

**Issue by wirecutter313** [Zimbra-Community/pgp-zimlet#216]
An error occurred while initializing the zimlet "tk_barrydegraaff_zimbra_openpgp". Please notify administrator.

TypeError: this.handlerObject._init is not a function

Not sure what the issue is.

**Comment by barrydegraaff** [comment]
This is a regression in 8.7.7, you can work around it by installing the latest version of pgp zimlet.

And flush your server and browser cache.


Meanwhile we are working on fixing it upstream here:
https://github.com/Zimbra/zm-ajax/pull/5

**Comment by wirecutter313** [comment]
Followed the process on the Readme.md and got the same error after 

[root@mail ~]# rm -Rf /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_zimbra_openpgp/
[root@mail ~]# su zimbra       
[zimbra@mail ~] wget https://github.com/Zimbra-Community/pgp-zimlet/releases/download/2.7.1/tk_barrydegraaff_zimbra_openpgp.zip -O /tmp/tk_barrydegraaff_zimbra_openpgp.zip
[zimbra@mail ~] zmzimletctl deploy /tmp/tk_barrydegraaff_zimbra_openpgp.zip
[zimbra@mail ~] zmmailboxdctl restart

Getting this is Safari:
An error occurred while initializing the zimlet "tk_barrydegraaff_zimbra_openpgp". Please notify administrator.
TypeError: this.handlerObject._init is not a function. (In 'this.handlerObject._init(this,DwtShell.getShell(window))', 'this.handlerObject._init' is undefined)

Getting this in Chrome and Firefox:
An error occurred while initializing the zimlet "tk_barrydegraaff_zimbra_openpgp". Please notify administrator.
TypeError: this.handlerObject._init is not a function

**Comment by barrydegraaff** [comment]
It is probably a cache issue, I just deployed on a fresh 8.7.7 and it worked fine.

What version of Zimbra are you on?

on the server: zmprov fc all

Did you close your browser and removed temporary internet files? If it still does not work, restart Zimbra.

**Comment by wirecutter313** [comment]
Ya that didnt' work, still having the issue. 

Release 8.7.7.GA.1787.UBUNTU16.64 UBUNTU16_64 FOSS edition.

I've cleared the server cache, and new browsers

**Comment by barrydegraaff** [comment]
Its probably the js optimizer, please try version 2.7.2.

If it still does not work, try google chrome, hit f12 and then reload zimbra and watch the console tab.

**Comment by nikonaum** [comment]
I have zimlet owncloud installed ver. 0.8.1 and I have the same error message and while testing I found that the account that gives no error is the one with owncloud zimlet enabled and the one with zimlet NOT ENABLED gives errors. I have issues with zimlet zimbra_secure_email, again the account with owncloud zimlet enabled works but the others don't. So I'll do some testing there as well and report back here.
P.S. I didn't had time to update owncloud zimlet to fix the issue I reported to you earlier, I'll check the situation after update as well.

**Comment by barrydegraaff** [comment]
This is probably because there is a bug in Zimbra and I deploy patches with my zimlets.

This is probably
https://github.com/Zimbra/zm-ajax/pull/5

anyway, this does not seem like a bug in owncloud zimlet.

Barry

**Comment by nikonaum** [comment]
@barrydegraaff  Yes, I'm aware that PGP zimlets are different. So what I found out is that even with your own owncloud and PGP zimlets (latest versions) installed the PGP one made by you (and even the iway's one) is giving errors and is not working If I don't enable the ownclod zimlet. I installed Owncloud zimlet with doing this after the shell script:
java -jar /tmp/webdav-client-installer.3KzV7Fva/upgrade/prop2xml.jar tk_barrydegraaff_owncloud_zimlet /opt/zimbra/lib/ext/ownCloud/config.properties /opt/zimbra/zimlets-deployed/tk_barrydegraaff_owncloud_zimlet/config_template.xml
P.S. You are blazing fast with your postings. Thank you very much.

**Comment by barrydegraaff** [comment]
yeah, maybe I included the patch only in owncloud, not pgp zimlet.

I will check friday. You can look at the source and look for 'bug' 'fix' or something like that in the comments.

**Comment by barrydegraaff** [comment]
Maybe its something else... 

on what zimbra version are you?


https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/zimlet/tk_barrydegraaff_owncloud_zimlet.js#L1380

https://github.com/Zimbra-Community/pgp-zimlet/blob/stable/tk_barrydegraaff_zimbra_openpgp/tk_barrydegraaff_zimbra_openpgp.js#L874

**Comment by barrydegraaff** [comment]
In Google Chrome go to the log-in screen for your zimbra but append to the url ?dev=1

Then hit f12 to open developer console and open the console tab,

Log in, and see where the error is, unfortunately things are a bit more difficult in last
view Zimbra versions, as this error may be cached with the dialog you are seeing.

Hopefully you can see some red lines in the console, and you can click on the links
behind them to see what zimlet has the issue.

**Comment by nikonaum** [comment]
OK, here is what I get. When I login into zimbra with ?dev=1 append to the login url I get absolutely no errors, no matter which zimlet is enabled in preferences. But when I login the usual way with ownloud zimlet DISABLED I get this in chromium developer console:

 Uncaught TypeError: Cannot read property 'handlerObject' of null

    at Zimlets-nodev_all.js.zgz?language=en&country=US&cosId=e00428a1-0c00-11d9-836a-000d93afea2a:40138
(anonymous) @ Zimlets-nodev_all.js.zgz?language=en&country=US&cosId=e00428a1-0c00-11d9-836a-000d93afea2a:40138
and the link is to this url:
https://my_FQDN/service/zimlet/res/Zimlets-nodev_all.js.zgz?language=en&country=US&cosId=e00428a1-0c00-11d9-836a-000d93afea2a

and when I click on It it goes to line number 40138 with the following content:
var zimletInstance=appCtxt._zimletMgr.getZimletByName("tk_barrydegraaff_owncloud_zimlet").handlerObject;

P.S. I'm running zimbra ZCS-8.7.11 Opensource Edition

**Comment by barrydegraaff** [comment]
It has to be a cache issue, on the server: zmprov fc all and zmmailboxdctl restart 

If that does not work, remove owncloud and try again. 

https://github.com/Zimbra-Community/owncloud-zimlet#un-installing 

And then re-install with all the default options in the installer

**Comment by nikonaum** [comment]
It's not a cache issue. I ran the zmprov fc all multiple times. Just one question. Should I ran the following command after auto installing the ownclod zimlet:
java -jar /tmp/webdav-client-installer.3KzV7Fva/upgrade/prop2xml.jar tk_barrydegraaff_owncloud_zimlet /opt/zimbra/lib/ext/ownCloud/config.properties /opt/zimbra/zimlets-deployed/tk_barrydegraaff_owncloud_zimlet/config_template.xml
AND
zmzimletctl configure /opt/zimbra/zimlets-deployed/tk_barrydegraaff_owncloud_zimlet/config_template.xml
**As prompted by the auto installer script.**

**Comment by nikonaum** [comment]
It's OK now. I removed owncloud zimlet completely and installed It again without touching any of the other OpenPGP zimlets and there is no more errors. Some small issue with importing public key to the zimbra_secure_email zimlet but this is for the zimlet's git hub issue page.
