### ISSUE TITLE
issue with gpg4win

### ISSUE THREAD

**Issue by Xardas999** [Zimbra-Community/pgp-zimlet#217]
Dear Barry

gpg4win doesn't decrypt automatically the emails, where the PGP-block is located in the message body (not in the encrypted.asc attachment). 
Are you aware about this issue, and is there anything to do with it? 

Outlook/Office 2007 
Windows Server 2008 R2
GPG4win gpg4win 2.3.3 (latest)

**Comment by Xardas999** [comment]
closed. In the Features section [https://github.com/Zimbra-Community/pgp-zimlet/wiki](url) it has mentioned that currently the zimlet supports only PGP-Inline specification fpr SENDing mails. It means they go in the messages body.

**Comment by tuanta** [comment]
You may consider another implementation: https://github.com/iwayvietnam/openpgp-secure-zimlet
