### ISSUE TITLE
PGP/MIME for sending

### ISSUE THREAD

**Issue by Xardas999** [Zimbra-Community/pgp-zimlet#218]
Dear Barry,

Could you let us know please, have you got in the roadmap to implement PGP/MIME specifications for sending mails?

**Comment by barrydegraaff** [comment]
Hello,

I will not implement pgp/mime for sending, also thinking about deprecating this 
Zimlet. You may try https://github.com/iwayvietnam/openpgp-secure-zimlet

**Comment by Xardas999** [comment]
thank you for the sincerity and for the recommendation.

**Comment by Xardas999** [comment]
Hello

It will be much better if you decide to continue to develop openPGP zimlet…
 After trying that one I think to return to your version… It works much better even without PGP/MIME.

**Comment by barrydegraaff** [comment]
Thanks for the feedback.

So far I noted that openpgp-secure-zimlet cannot encrypt draft messages, that is something
I use frequently.

Also I am running a pilot with openpgp-secure-zimlet in my company, I believe maybe it has better
compatibility with other pgp implementations, but my users are very good at finding issues.

Anyway, the pgp-zimlet would need a full rewrite, as a lot of lessons where learned.

I may undo the deprecation, but pgp-zimlet will require a lot of time.


Barry

**Comment by Xardas999** [comment]
it’s nice! Hope to hear from you soon.

**Comment by barrydegraaff** [comment]
Can you explain what you did not like in the Vietnamese version? So I can have the feedback. Thanks

**Comment by barrydegraaff** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Hello All,

As some of you may know a month back I announced the deprecation of Zimbra OpenPGP Zimlet.

A number of people reached out to me, expressing they prefer to keep using Zimbra OpenPGP Zimlet.

So I decided to un-deprecate and resume active development, I estimate I need 2 weeks of dev
time to implement improvements, find that time/budget will be a challenge.

In the meantime I released a maintenance update 2.7.3.

https://github.com/Zimbra-Community/pgp-zimlet


Kind regards,

Barry de Graaff
Zeta Alliance Founder
www.zetalliance.org

+31 617 220 227
Skype: barrydegraaff.tk
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
-----BEGIN PGP SIGNATURE-----
Version: OpenPGP.js v2.5.4
Comment: http://openpgpjs.org

wkYEAREIABAFAllFjVcJEHJd3RVtNqLQAACqQwCdG7iAmeam4KhPNqedLbCb
CDGqudoAnA9sOvoEIsjlWdd0p6EZM88q7tBL
=LanX
-----END PGP SIGNATURE-----

**Comment by Xardas999** [comment]
hei, Barry

Sorry for the delay, I seen your message but couldn’t find time on this week to work it out. I will summarize the things your asked very soon. 

BR, Konsta
