### ISSUE TITLE
Can not create key pair  "openpgp.generateKey is not a function"

### ISSUE THREAD

**Issue by mikenam** [Zimbra-Community/pgp-zimlet#221]
Hi, I am using the lastest version of the zimlet (07.2017) and Zimbra 8.6.

When i try to create the key pair, I get "openpgp.generateKey is not a function", so keys can not be created!

Any ideas?

**Comment by barrydegraaff** [comment]
I'll look into it end of next week

**Comment by barrydegraaff** [comment]
Can you try and install following this wiki: https://github.com/Zimbra-Community/pgp-zimlet/wiki/Install-from-git

It works here.
