### ISSUE TITLE
Have md5sum and/or sha256 sum for downloaded .zip file

### ISSUE THREAD

**Issue by AJRepo** [Zimbra-Community/pgp-zimlet#222]
I see in the installation directions it states: 

wget https://github.com/Zimbra-Community/pgp-zimlet/releases/download/2.7.4/tk_barrydegraaff_zimbra_openpgp.zip -O /tmp/tk_barrydegraaff_zimbra_openpgp.zip

but I didn't see anywhere to do a hash check on the downloaded file. 

Can you, in your documentation, when you release the .zip file for download, add the SHA256 and/or md5 hash values for the zip file? (you could sign the binary .zip too)

**Comment by barrydegraaff** [comment]
Hello AJRepo,

I could do that, but I won't as there is not so much (no funding at all) for pgp-zimlet.

But thanks for asking.

Regards, Barry
