### ISSUE TITLE
Remove PGP header / footer

### ISSUE THREAD

**Issue by tomalbers** [Zimbra-Community/pgp-zimlet#224]
Would it be possible to only show the part between -----BEGIN PGP SIGNED MESSAGE-----
And remove the rest? Maybe replace it with a border to show which part was properly signed.

**Comment by tuanta** [comment]
Please checkout this Zimlet: https://github.com/iwayvietnam/openpgp-secure-zimlet
It support PGP/MIME fully.

**Comment by barrydegraaff** [comment]
Yeah, we did that in the past, but ran into issues when people do reply/forward. So this one, we are going to let it stay as is.
