### ISSUE TITLE
How to migrate public key between zimbra servers?

### ISSUE THREAD

**Issue by nagual13** [Zimbra-Community/pgp-zimlet#226]
Good day! Please tell me how to migrate public key between zimbra servers. I have a task to transfer between public key servers from users ' accounts.

**Comment by barrydegraaff** [comment]
You can migrate them using the Zextras backup and restore or Zimbra Network Modules NG, as they are stored in the LDAP.

You  can also script the stuff if you like.

**Comment by nagual13** [comment]
I pulled out of the ldap server source entry with the key: zimbraZimletUserProperties: tk_barrydegraaff_zimbra_openpgp:zimbra_openpgp_pubkeys2:-----BEGIN PGP PUBLIC KEY BLOCK-----
I insert in ldap of the server of destination-but in the web form of the plug-in of OpenPGP the key under such number does not appear.  Only the keys entered via the web form are saved.

**Comment by barrydegraaff** [comment]
There may be some delay, try to reload your browser, flush cache and all that.

Also keep in mind that you may easily erase other `zimbraZimletUserProperties` ldap settings if you try and update just one `zimbraZimletUserProperties`
