### ISSUE TITLE
Migrate public key from plugin between servers

### ISSUE THREAD

**Issue by nagual13** [Zimbra-Community/pgp-zimlet#227]
I pulled out of the ldap server source entry with the key: zimbraZimletUserProperties: tk_barrydegraaff_zimbra_openpgp:zimbra_openpgp_pubkeys2:-----BEGIN PGP PUBLIC KEY BLOCK-----
I insert in ldap of the server of destination-but in the web form of the plug-in of OpenPGP the key under such number does not appear. Only the keys entered via the web form are saved.

**Comment by nagual13** [comment]
Can be still need where the burn this the key?

**Comment by barrydegraaff** [comment]
If you inserted it correctly in LDAP, it should show in the web-ui. But it is cached, so flush your server and browser cache and wait a while to see it appear.
