### ISSUE TITLE
No certificate found

### ISSUE THREAD

**Issue by scylla999** [Zimbra-Community/pgp-zimlet#229]
Hello,
I cannot seem to get this Zimlet (version 2.7.5) working with Zimbra 8.8.9_GA_3042 (build 20181009041245).
I get an error that starts with 'encryption failed, No certificate found).   Recipients public key is in the contact notes and my private key is registered in the Zimlet (see screenshot):
![zimbra-pgp-errors_2018-11-21_10h44_anon](https://user-images.githubusercontent.com/24919069/48864497-bdcee700-ed9a-11e8-85d3-0145d2eeb491.jpg)
Thank You!

**Comment by barrydegraaff** [comment]
Probably you also installed s/mime or some other Zimlet. Because PGP Zimlet does not have a `Sign and Encrypt` button. Not does it work from `Compose in a new window`.

The UI looks like so:
http://barrydegraaff.github.io/help/

**Comment by scylla999** [comment]
Yes you're right.   I disabled the S/MIME functionality.   However, now I do not have the 'Encrypt' or 'Sign' button like in your user guide in the 'compose' window'.   There's still something missing.

**Comment by barrydegraaff** [comment]
try and install like so:
https://github.com/Zimbra-Community/pgp-zimlet/wiki/Install-from-git

Then it should work, also, when installed, it should no longer allow to compose in a new window.
