### ISSUE TITLE
Decryption of PGP messages stopped working in 8.8.11_GA_3737

### ISSUE THREAD

**Issue by oliverbross** [Zimbra-Community/pgp-zimlet#230]
As per the title of this post, the decryption does not work anymore in the latest version of zimbra - 8.8.11_A_3737, as well as actually it stopped working after the middle december 2018 updates.

Please, can you have a look as this issue is preventing users using such a fantastic tool?

Many thanks

**Comment by barrydegraaff** [comment]
It works well here, perhaps you can give me a test account on your server, so I can check?

Send it to info@barrydegraaff.tk

**Comment by oliverbross** [comment]
No worries Barry, I have sent you the details few min ago.

**Comment by barrydegraaff** [comment]
It seems to work well on the test account as well.

Perhaps it is a cache issue. 

Try and remove the zimlet, deploy in development mode like so:
https://github.com/Zimbra-Community/pgp-zimlet/wiki/Install-from-git

Flush your browser cache and try again.

You can also open a developer console, in google chrome hit f12 and see if there are any error messages in the Console tab.

**Comment by barrydegraaff** [comment]
Works on 8.8.12
