### ISSUE TITLE
Move OpenPGP from Zimlets to the top level menu?

### ISSUE THREAD

**Issue by serveria** [Zimbra-Community/pgp-zimlet#231]
Hi,

Thanks for a wonderful zimlet. I wonder if there's a way to move OpenPGP from Zimlets to the top level menu of Zimbra (along with Mail Folders/Searches/Tags/Zimlets etc)?

**Comment by barrydegraaff** [comment]
Short answer, NO, long answer, maybe it will help to auto-expand the Zimlets menu?
So users at least see the Zimlet. Using this command:

zmprov mc default zimbraPrefZimletTreeOpen TRUE
