### ISSUE TITLE
Zimbra OpenPGP Zimlet doesn't handle PGP/Inline correctly

### ISSUE THREAD

**Issue by robert-scheck** [Zimbra-Community/pgp-zimlet#234]
The following e-mail (with PGP/Inline) is handled incorrectly by v2.7.5 in Zimbra 8.8.15:

```
Date: Fri, 14 Feb 2020 14:47:29 +0100
From: Bob Doe <bob@example.net>
To: Alice Average <alice@example.net>
Subject: PGP test

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2.0.22 (GNU/Linux)

[…]
-----END PGP MESSAGE-----

-- 
Bob Doe, Tester
Example Ltd.
Test Rd. 42
99999 Testing, AQ
```

The e-mail footer/signature after `-- ` is not shown at all once the e-mail has been decrypted: Only the decrypted content is shown. This is bad for e.g. public mailing lists (for signed parts with later appended mailing list information for unsubscribe etc.) or senders which are forced for whatever reason to use PGP/Inline). This is more or less how it looks currently:

```
Date: Fri, 14 Feb 2020 14:47:29 +0100
From: Bob Doe <bob@example.net>
To: Alice Average <alice@example.net>
Subject: PGP test

[Content of decrypted PGP/Inline]
```

As seen in some other e-mail clients, I would propose the following behaviour instead:

```
Date: Fri, 14 Feb 2020 14:47:29 +0100
From: Bob Doe <bob@example.net>
To: Alice Average <alice@example.net>
Subject: PGP test

[-- The following data is encrypted/signed --]
[Content of decrypted PGP/Inline]
[-- End of encrypted/signed data --]

-- 
Bob Doe, Tester
Example Ltd.
Test Rd. 42
99999 Testing, AQ
```

Note that the `[-- … --]` formatting above is just an example, it finally needs to make absolutely clear which part of the e-mail was encrypted or signed, if it wasn't the full MIME part.

**Comment by barrydegraaff** [comment]
I confirm the suggested behavior is better, but I do not plan to implement it any time soon.
