### ISSUE TITLE
No "encrypt message" button in new message header

### ISSUE THREAD

**Issue by jringoot** [Zimbra-Community/pgp-zimlet#238]
I have installed the latest version (2.7.6 https://github.com/Zimbra-Community/pgp-zimlet/releases)
The generated keys,

![Screenshot from 2021-01-15 11-48-55](https://user-images.githubusercontent.com/2686933/104716317-16566080-5728-11eb-8a8a-8aaa08de3ce1.png)

but I don't have the "encrypt message" button in the new message header 
![Screenshot from 2021-01-15 11-51-19](https://user-images.githubusercontent.com/2686933/104716432-3a19a680-5728-11eb-9bf7-ab115cf9b5f0.png)

I run Zimbra 9.0.0_GA_3990 (build 20201210230251)
No button in modern client either

How to get that button, or otherwise encrypt the message?

**Comment by barrydegraaff** [comment]
![Screenshot from 2021-01-22 09-45-20](https://user-images.githubusercontent.com/4353213/105467884-93d52000-5c96-11eb-9137-4a44e84bf0a6.png)

It still works, but maybe you `compose in a new window` or reply-inline, that does not work. Try using the reply button so it goes  to a new tab in the UI.

**Comment by jringoot** [comment]
Ok thanks, I removed the "Always compose in new window"
and now it works
![Screenshot from 2021-02-03 14-03-50](https://user-images.githubusercontent.com/2686933/106750919-c7199680-6628-11eb-8f5a-21a51141b64b.png)
