### ISSUE TITLE
ReferenceError openpgp is not defined

### ISSUE THREAD

**Issue by BorisM66** [Zimbra-Community/pgp-zimlet#244]
Hi! I have installed pgp-zimlet using instructions see in Readme file and I have this message error when I want to create a pair of key "ReferenceError : openpgp is not defined"
My Zimbra version is 8.8.815.GA.3869.UBUNTU16.64
Thanks for helping me

**Comment by BorisM66** [comment]
I see in firefox that failed here : 
var h=document.getElementsByTagName("HEAD").item(0);
var r=document.createElement("script");
r.type="text/javascript";
r.src=this.getResource("openpgp.js");
h.appendChild(r);
var t=this.getResource("openpgp.worker.js");
try{
setTimeout(function(){
openpgp.initWorker({
path:t}
)
}

**Comment by BorisM66** [comment]
I see also in console : 
GET https://<my-server-name>/service/zimlet/tk_barrydegraaff_zimbra_openpgp/openpgp.js [HTTP/2 404 Not Found 16ms]

**Comment by BorisM66** [comment]
Hi ! After different check of files no solutions find. 
I have made an dist-upgrade (16.04 to 18.04), and after 3h of bad moment due to the upgrade the error reported appear to be ok.
So the bug was with Ubuntu 16.04.6 and ZCS 8.8.15

**Comment by BorisM66** [comment]
ARF... After the week-end, come back to work and see that all zimlet pictures disappear again and the zimlet don't work again :/ Is there any possibilty to see logs of error ?

**Comment by barrydegraaff** [comment]
please try and install following these instructions: 
https://github.com/Zimbra-Community/pgp-zimlet/wiki/Install-from-git

**Comment by ErickSevillano** [comment]
Hola estoy intentando instalar el OpenPGP.
Seguí los pasos tal como describe el enlace https://github.com/Zimbra-Community/pgp-zimlet
Al hacer click en revisar revisar keyserver o submit keyserver me aparecen los errores adjuntos.
Soy nuevo en esto y tengo muchos ánimos de aprender, saludos.
![Captura1](https://user-images.githubusercontent.com/119626311/205146101-021743cb-c981-44fa-bcdf-8318989d219e.JPG)
![Captura3](https://user-images.githubusercontent.com/119626311/205146110-55e9c214-8523-445b-b332-67468cb9baa7.JPG)
